title: PropVyuh
description: "Your Chakravyuh against bad home loans. Strategize. Simulate. Strike."
theme: jekyll-theme-hacker
show_downloads: false

# SEO & metadata
url: ""
baseurl: "/PropVyuh"
lang: en

# Build
markdown: kramdown
kramdown:
  input: GFM
